### ISSUE TITLE
Move ControlledVocabulary to own repo

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/ARCTokenization#58]
ControlledVocabulary is not only needed in ARCTokenization but also in other projects that may rely on CV types (like, possibly, OBO.NET) or that could integrate the CV model in any other way.
Therefore, ControlledVocabulary should imo be in its own repo to circumvent circular dependencies with other repos on the one hand and to thin out the bloated ARCTokenization repo on the other.

What's your opinion on this, @kMutagene?

**Comment by kMutagene** [comment]
`ControlledVocabulary` is a standalone nuget package, which is built from a standalone project in the `ARCTokenization` repo. 

It makes sense to keep it there, since `ARCTokenization` (the project) is most affected of changes in `ControlledVocabulary` and that is reflected by having them next to each other via project dependencies (instead of nuget dependencies). There is a point to maybe make _every_ project in all our repos a standalone repo each, but since nuget updates are so slow to release once pushed to the registry, this would significantly slow down development in some repos, which is why we currently do not do that.

All of this does not prevent just adding a plain nuget reference to `ControlledVocabulary` in any other project thoguh.
